name: My CI/CD pipeline for DevOps Crash Course

on: 
  push:
    branches: [master]
    
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  ci_pipline:
    runs-on: ubuntu-latest
    steps:
    - name: Print my firstname and lastname
      run: echo "My name is Nikita Malov!"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
  cd_pipeline:
    needs: [ci_pipline]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Print my firstname and lastname
      run: echo "My name is Nikita Malov!"
    - name: Deploy page
      id: deployment
      uses: actions/deploy-pages@v2
